### ISSUE TITLE
Computerized Adaptive Tests (CAT) Support

### ISSUE THREAD

**Issue by aboudzakaria** [davemckain/qtiworks#69]
What are the plans for supporting or plugin-in Computerized Adaptive Test (CAT) engines?

**Comment by davemckain** [comment]
QTI 2.1 defines <customInteraction> and <customOperator> classes, providing a basic mechanism for plugging in 3rd party tools or adding in additional functionality. 

A project called MathAssess - funded from the same source as QTIWorks so therefore integrated into QTIWorks - developed some extensions for using the Maxima Computer Algebra System (http://maxima.sourceforge.net) to support more complex mathematical assessment items. The QTIWorks public demo shows some of these questions in operation.

You may be able to use these ideas to define and develop your extensions. However you'd need to do this yourself, and you'd have to run your own instance of QTIWorks in order to support these. You may also find that the customInteraction/customOperator extensions aren't so useful in the context of assessmentTests. (I.e. adaptive *tests* rather than adaptive *items*.) I suspect there weren't enough (any?) use cases developed for that scenario.

I can provide more details on the MathAssess specification if you'd like to look into possibly doing something similar yourself.

You may want to look at QTI 2.2 to see if that brings in anything that might be of use. (I have to admit I haven't looked at it closely yet.) However note that there are no plans to support QTI 2.2 in QTIWorks. 

Any further development of QTIWorks (other than bug fixes) would be contingent on finding a source of funding.

Hope that helps a bit!

**Comment by davemckain** [comment]
Closing this one as it has been dormant for a while.
